version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --port=8000 --host=0.0.0.0
    env_file:
      - .env
    ports:
      - "8000:8000"
